config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'welcome', to: "dashboard#welcome"
  root to: "dashboard#welcome"
  resources :shows do
    resources :bookings
  end

  namespace :admin do
    resources :movies
    resources :screens, only: [:index] do
      resources :shows, only: [:index, :new, :create, :show] do
        resources :seats, only: [:index]
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :show
  belongs_to :seat
end

app/models/movie.rb
class Movie < ApplicationRecord

  has_many :shows

  validates :name, presence: true

  def self.dropdown_list
    all.collect{|movie| [movie.name, movie.id]}
  end

end

app/models/multiplex.rb
class Multiplex < ApplicationRecord
  has_many :screens
end

app/models/screen.rb
class Screen < ApplicationRecord
  belongs_to :multiplex
  has_many :seats
  has_many :shows

  after_create :create_seats

  def create_seats
    30.times do |n|
      Seat.create(code: "S#{n+1}", type: "silver", screen_id: id)
    end

    40.times do |n|
      Seat.create(code: "G#{n+1}", type: "gold", screen_id: id)
    end

    30.times do |n|
      Seat.create(code: "P#{n+1}", type: "platinum", screen_id: id)
    end
  end

  def self.dropdown_list
    all.pluck(:name, :id)
  end
end

app/models/seat.rb
require 'csv'

class Seat < ApplicationRecord
  belongs_to :screen
  has_many :bookings
  has_many :shows, through: :bookings

  self.inheritance_column = 'inheritance_type'

  TYPES = { "silver": "Silver", "gold": "Gold", "platinum": "Platinum" }
  COSTS = { "silver": 150, "gold": 200, "platinum": 300 }


  def seat_style(show_id)
    return "sold" if bookings.where(show_id: show_id).exists?
  end

  def is_booked(show_id)
    shows.where(id: show_id).present? ? 'YES' : 'NO'
  end

  def self.to_csv(show_id)
    headers = ["Seat", "Type", "Is Booked"]
    CSV.generate(headers: true) do |csv|
      csv << headers
      all.each do |seat|
        csv << [seat.code, TYPES.as_json[seat.type], seat.is_booked(show_id)]
      end
    end
  end

end

app/models/show.rb
class Show < ApplicationRecord
  belongs_to :movie
  belongs_to :screen

  has_many :bookings

  scope :filter_by_movie_id, -> (movie_id) { where movie_id: movie_id }
  scope :filter_by_time_slot, -> (timings) { where time_slot: timings }
  scope :filter_by_date, -> (date) { where date: date }

  TIMINGS = { "afternoon": "12:00pm - 3:00pm",
    "evening": "4:00pm - 7:00pm", "night": "8:00pm - 11:00pm" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < ApplicationController

  def index
    @movies = Movie.all.order(:name)
  end

  def new
    @movie = Movie.new
    respond_to do |format|
      format.js
    end
  end

  def create
    Movie.create(permit_params(params))
    redirect_to admin_movies_path(date: params[:date])
  end

  def edit
    @movie = Movie.find_by(id: params[:id])
  end

  def update
    Movie.find_by(id: params[:id]).update(permit_params(params))
    redirect_to admin_movies_path(date: params[:date])
  end

  private

  def permit_params(params)
    params.require(:movie).permit(:name)
  end
end

app/controllers/admin/screens_controller.rb
class Admin::ScreensController < ApplicationController

  def index
    @screens = Screen.all
    respond_to do |format|
      format.js { render :js => "window.location='#{ admin_screens_path(date: params[:date]) }'" }
      format.html { render :index }
    end
  end

end

app/controllers/admin/seats_controller.rb
class Admin::SeatsController < ApplicationController

  def index
    show = Show.find_by(id: params[:show_id])
    screen = show.screen
    respond_to do |format|
      format.csv { send_data screen.seats.to_csv(params[:show_id]), filename: "#{screen.name}-#{show.date}.csv" }
    end
  end

end

app/controllers/admin/shows_controller.rb
class Admin::ShowsController < ApplicationController

  def new
    @show = Show.new
  end

  def create
    show_params = permit_params(params)
    show = Show.create(show_params)
    redirect_to admin_screens_path(date: show.date)
  end

  def show
    @show = Show.find_by(id: params[:id])
    @seats = @show.screen.seats
  end

  private

  def permit_params(params)
    params.require(:show).permit(:screen_id, :date, :movie_id, :time_slot)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    admin_screens_path(date: Date.today)
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_before_action :authenticate_user!

  def new
    @show = Show.find_by(id: params[:show_id])
    @seats = @show.screen.seats
  end

  def create
    @book = "ssup"
    params[:seat_ids].each{ |seat_id| Booking.create(seat_id: seat_id, show_id: params[:show_id]) }
    seat_codes = Seat.where(id: params[:seat_ids]).pluck(:code).join(", ")
    render :json => {:success => true, :data => {seat_codes: seat_codes}}, :status => 200
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  skip_before_action :authenticate_user!

  def welcome
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @shows = Show.all.includes(:bookings)
    filtering_params(params).each do |key, value|
      @shows = @shows.public_send("filter_by_#{key}", value) if value.present?
    end
    respond_to do |format|
      format.js { render :js => "window.location='#{ shows_path(movie_id: params[:movie_id],
        date: params[:date], time_slot: params[:time_slot] ) }'" }
      format.html { render :index }
    end

  end

  private

  def filtering_params(params)
    params.slice(:movie_id, :time_slot, :date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def dashboard
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/movies/_edit.haml
.modal-header
  %h4#myModalLabel.modal-title Update movie
  %button.close{"data-dismiss" => "modal", :type => "button"} x
.modal-body
  = simple_form_for @movie, url: admin_movie_path(@movie.id, date: params[:date]) do |f|
    .form-group.row
      .col-sm-12.mb-3.mb-sm-0
        = f.text_field :name, label: false, placeholder: "Movie Name", class: "form-control", required: true
    = f.submit "Save", class: 'btn btn-user btn-primary btn-block'

app/views/admin/movies/_new.haml
.modal-header
  %h4#myModalLabel.modal-title Add a Movie
  %button.close{"data-dismiss" => "modal", :type => "button"} x
.modal-body
  = simple_form_for @movie, url: admin_movies_path(date: params[:date]) do |f|
    .form-group.row
      .col-sm-12.mb-3.mb-sm-0
        = f.text_field :name, label: false, placeholder: "Movie Name", class: "form-control", required: true
    = f.submit "Add", class: 'btn btn-user btn-primary btn-block'

app/views/admin/movies/edit.js.haml
$("#modal-window").find(".modal-content").html("#{escape_javascript(render 'edit')}");
$("#modal-window").modal();

app/views/admin/movies/index.haml
.card.shadow.mb-4.mt-4
  .card-header.py-3
    .row
      .col-lg-10
        %h6.m-0.font-weight-bold.text-info Movies List
      .col-lg-2
        = link_to new_admin_movie_path(date: params[:date]),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-info btn-circle'} do
          %i.fa.fa-plus{title: "Add new movie"}
        #modal-window.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog"}
          .modal-dialog{:role => "document"}
            .modal-content.mt-4
        = link_to admin_screens_path(date: params[:date]), {class: 'btn btn-warning btn-circle'} do
          %i.fa.fa-close{title: "Back to Screens"}

  .card-body
    .row
      - @movies.each do |movie|
        .col-xl-3.col-md-6.mb-4
          .card.shadow.h-100.py-2.border-left-info.border-bottom-info
            .card-body
              .row.no-gutters.align-items-center
                .col-10
                  .text.mb-0.font-weight-bold.text-secondary=movie.name
                .col-2.float-right
                  = link_to edit_admin_movie_path(id: movie.id, date: params[:date]),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-warning btn-sm btn-circle'} do
                    %i.fa.fa-pencil{title: "Edit"}
                  #modal-window.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog"}
                    .modal-dialog{:role => "document"}
                      .modal-content.mt-4

app/views/admin/movies/new.js.haml
$("#modal-window").find(".modal-content").html("#{escape_javascript(render 'new')}");
$("#modal-window").modal();

app/views/admin/screens/_show_details.haml
- @screens.each do |screen|
  .col-xl-12.col-md-6.mb-4
    .card{class: "shadow border-left-warning"}
      .card-header.py-3
        .row
          .col-10
            %span.text.mb-0.font-weight-bold.text-secondary=screen.name
          .col-2.float-right
            = link_to new_admin_screen_show_path(screen.id, date: params[:date]), {class: 'btn btn-sm btn-success btn-circle'} do
              %i.fa.fa-plus{title: "Add a Show"}

      .card-body
        - shows = screen.shows.public_send("filter_by_date", date)
        - if shows.present?
          - shows.each do |show|
            .row.no-gutters.align-items-center.mb-1
              .col-2
                .text.text-info= Show::TIMINGS.as_json[show.time_slot]
              .col-3
                .text.font-weight-bold.text-secondary.mb-1=show.movie.name
              .col-3
                .text.font-weight-bold.text-secondary.mb-1="#{show.bookings.count} Seats Booked"
              .col-4
                %a.btn.btn-warning.btn-sm.btn-icon-split{:href => admin_screen_show_seats_path(screen.id, show.id, format: "csv")}
                  %span.icon.text-white-50
                    %i.fa.fa-download
                  %span.text Download CSV
                %a.btn.btn-info.btn-sm.btn-icon-split{:href => admin_screen_show_path(screen.id, show.id)}
                  %span.icon.text-white-50
                    %i.fa.fa-eye
                  %span.text View Bookings

        - else
          .row.no-gutters.align-items-center.mb-1
            .col-3
              .text.font-weight-bold.text-info.mb-1 No Shows Scheduled Yet. Add Now
            .col-1
              = link_to new_admin_screen_show_path(screen.id, date: params[:date]), {class: 'btn btn-sm btn-success btn-circle'} do
                %i.fa.fa-plus{title: "Add a Show"}

app/views/admin/screens/index.haml
.card.shadow.mb-4.mt-4
  .card-header.py-3
    .row
      .col-lg-10
        %h3.text.m-0.font-weight-bold.text-info Multiplex Screens - Show details
      .col-lg-2
        = link_to root_path, {class: 'btn btn-warning btn-circle float-right'} do
          %i.fa.fa-home{title: "Home"}
        = link_to destroy_user_session_path, method: :delete, class: "nav-link text-danger float-right" do
          %i.fa.fa-power-off
          %span Logout
    .row.mt-4
      .col-1.text-secondary.font-weight-bold.float-right
        Date:
      .col-2
        = date_field_tag "date", params[:date], class: 'form-control', disabled: false
      .col-lg-9
        %a.btn.btn-sm.float-right.btn-info.btn-icon-split{:href => admin_movies_path(date: params[:date])}
          %span.icon.text-white-50
            %i.fa.fa-eye
          %span.text Movies list

  .card-body#screenDetails
    = render partial: 'show_details', locals: {date: params[:date]}

:javascript
  $("#date").on('change', function(){
    get_shows();
  });

  function get_shows(){
    date = $("#date").val()
    $.ajax({
      url: "/admin/screens?date=" + date,
      type: "GET",
      success:function(data){
      }
    })
  }

app/views/admin/shows/new.haml
%body.bg-gradient-primary
  .container
    .card.o-hidden.border-0.shadow-lg.my-5
      .card-body.p-0
        .row
          .col-lg-4.d-none.d-lg-block.bg-register-image
          .col-lg-8
            .p-5
              .text-center
                = link_to admin_screens_path(date: params[:date]), {class: 'btn btn-danger btn-circle float-right'} do
                  %i.fa.fa-close{title: "Cancel"}
                %h1.h4.text-gray-900.mb-4 Add a New Show
                .col-lg-2

              = simple_form_for @show, url: admin_screen_shows_path do |f|
                .form-group.row
                  .col-sm-6.mb-3.mb-sm-0
                    = f.input :screen_id, input_html: {class: 'form-control'}, collection: Screen.dropdown_list, selected: params[:screen_id], required: true, readonly: true
                  .col-sm-6
                    .label.mb-1 * Date
                    = f.date_field :date, as: :date, value: params[:date], class: 'form-control', required: true, label: "Date", readonly: true
                .form-group.row
                  .col-sm-6.mb-3.mb-sm-0
                    = f.input :movie_id, input_html: {class: 'form-control'}, collection: Movie.dropdown_list, required: true
                  .col-sm-6
                    = f.input :time_slot, input_html: {class: 'form-control'}, collection: Show::TIMINGS.as_json.invert.to_a, required: true
                = f.submit "Add", class: 'btn btn-user btn-primary btn-block'

app/views/admin/shows/show.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AdminPanel
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    %link{:href => "https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i", :rel => "stylesheet"}/
    %body#page-top
      #wrapper
      #content-wrapper.d-flex.flex-column
        #content
          .container-fluid
            .card.shadow.mb-4.mt-4
              .card-header.py-3
                .row
                  .col-lg-10
                    %h3.text.m-0.font-weight-bold.text-info= @show.screen.name + " - " + @show.date.to_s
                  .col-lg-2
                    = link_to admin_screens_path(date: @show.date), {class: 'btn btn-danger btn-circle float-right'} do
                      %i.fa.fa-close{title: "close"}
              .card-body
                .row
                  .col-1.mb-3
                  .col-5.mb-3
                    .btn.btn-warning.btn-block SCREEN
                .row
                  .col-8
                    .row
                      - @seats.each do |seat|
                        .col-1.mb-1.ml-2
                          .card.seat{class: "#{seat.type} #{seat.seat_style(params[:id])}", id: "#{seat.id}"}
                            .card-body.seat-body
                              .row.no-gutters.align-items-center
                                .col.mr-2
                                  .text-md.mb-0.font-weight-bold.text-secondary=seat.code
                                  .text-xs.mb-1.text-primary="₹#{Seat::COSTS.as_json[seat.type]}"
                  .col-4
                    .row
                      %h1.h4.text-gray-900.mb-4 Show Details:
                    .row
                      .col-4
                        .text.font-weight-bold.text-warning.mb-1 Movie:
                      .col-6
                        .text.font-weight-bold.text-info.mb-1= @show.movie.name
                    .row.mt-2
                      .col-4
                        .text.font-weight-bold.text-warning.mb-1 Time:
                      .col-6
                        .text.font-weight-bold.text-info.mb-1= Show::TIMINGS.as_json[@show.time_slot]
                    .row.mt-2
                      .col-4
                        .text.font-weight-bold.text-warning.mb-1 Screen:
                      .col-6
                        .text.font-weight-bold.text-info.mb-1= @show.screen.name

                    .row.mt-4
                      %h1.h4.text-gray-900.mb-4 Booking Details:
                    .row.mt-2
                      .col-1
                        .grey-box
                      .col-6
                        .text.font-weight-bold.text-info.mb-1 Available
                      .col-2
                        .text.font-weight-bold.text-info.mb-1= 100 - @show.bookings.count
                    .row.mt-2
                      .col-1
                        .red-box
                      .col-6
                        .text.font-weight-bold.text-info.mb-1 Sold
                      .col-2
                        .text.font-weight-bold.text-info.mb-1= @show.bookings.count

app/views/bookings/_summary.haml
.modal-content.mt-4
  .modal-header
    %h4#exampleModalLabel.modal-title Your Booking Summary
  .modal-body
    .row
      .col-3
      .col-8
        %h4.font-weight-bold.text-success Booking Successful!
    .row
      .col-5
      .col-5
        .btn.btn-success.btn-circle.btn-lg
          %i.fa.fa-check
    .row.mt-4
      .col-12
        .row
          .col-4
            .text.float-right.font-weight-bold.text-warning.mb-1 Movie:
          .col-8
            .text.font-weight-bold.text-info.mb-1= @show.movie.name
        .row.mt-2
          .col-4
            .text.float-right.font-weight-bold.text-warning.mb-1 Time:
          .col-8
            .text.font-weight-bold.text-info.mb-1= Show::TIMINGS.as_json[@show.time_slot]

        .row.mt-2
          .col-4
            .text.float-right.font-weight-bold.text-warning.mb-1 Seats:
          .col-8
            .text.font-weight-bold.text-info.mb-1#selectedSeatCodes

        .row.mt-2
          .col-4
            .text.float-right.font-weight-bold.text-warning.mb-1 Cost:
          .col-8
            .text.font-weight-bold.text-info.mb-1#totalCost2


        .row.mt-4.ml-4
          .col-3
            = link_to 'Book More', new_show_booking_path(params[:show_id]),  {class: 'btn btn-success'}
          .col-3
            = link_to 'Back to Shows', shows_path(date: @show.date),  {class: 'btn btn-info'}
          .col-3
            = link_to 'Go to Home', root_path,  {class: 'btn btn-danger'}

app/views/bookings/new.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AdminPanel
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    %link{:href => "https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i", :rel => "stylesheet"}/
    %body#page-top
      #wrapper
      #content-wrapper.d-flex.flex-column
        #content
          .container-fluid
            .card.shadow.mb-4.mt-4
              .card-header.py-3
                .row
                  .col-lg-10
                    %h3.text.m-0.font-weight-bold.text-info Select Seats
                  .col-lg-2
                    = link_to shows_path(date: @show.date), {class: 'btn btn-danger btn-circle float-right'} do
                      %i.fa.fa-close{title: "Cancel"}

              .card-body
                .row
                  .col-1.mb-3
                  .col-5.mb-3
                    .btn.btn-warning.btn-block SCREEN
                .row
                  .col-8
                    .row
                      - @seats.each do |seat|
                        .col-1.mb-1.ml-2
                          .card.seat{class: "#{seat.type} #{seat.seat_style(params[:show_id])}", id: "#{seat.id}"}
                            .card-body.seat-body
                              .row.no-gutters.align-items-center
                                .col.mr-2
                                  .text-md.mb-0.font-weight-bold.text-secondary=seat.code
                                  .text-xs.mb-1.text-primary="₹#{Seat::COSTS.as_json[seat.type]}"
                  .col-4
                    .row
                      %h1.h4.text-gray-900.mb-4 Booking Details:
                    .row
                      .col-4
                        .text.font-weight-bold.text-warning.mb-1 Movie:
                      .col-6
                        .text.font-weight-bold.text-info.mb-1= @show.movie.name
                    .row.mt-2
                      .col-4
                        .text.font-weight-bold.text-warning.mb-1 Time:
                      .col-6
                        .text.font-weight-bold.text-info.mb-1= Show::TIMINGS.as_json[@show.time_slot]

                    .row.mt-2
                      .col-4
                        .text.font-weight-bold.text-warning.mb-1 Seats:
                      .col-6
                        .text.font-weight-bold.text-info.mb-1#seatCount

                    .row.mt-2
                      .col-4
                        .text.font-weight-bold.text-warning.mb-1 Cost:
                      .col-6
                        .text.font-weight-bold.text-info.mb-1#totalCost

                    .row.mt-5
                      .col-1.mb-3
                      .col-8.mb-3
                        %button#confirmButton{class: 'btn btn-success btn-lg btn-block disabled'} Confirm Booking
                        #modal-window.modal.hide.fade{"aria-hidden" => "true", "data-backdrop" => "static", "data-keyboard" => "false", "aria-labelledby" => "myModalLabel", :role => "dialog"}
                          .modal-dialog{:role => "document"}
                            = render partial: 'summary'

                    .row.mt-5
                      .col-1#totalCost
                        .green-box
                      .col-6
                        .text.font-weight-bold.text-info.mb-1 Selected
                    .row.mt-2
                      .col-1
                        .grey-box
                      .col-6
                        .text.font-weight-bold.text-info.mb-1 Available
                    .row.mt-2
                      .col-1
                        .red-box
                      .col-6
                        .text.font-weight-bold.text-info.mb-1 Sold

:javascript
  selectedSeatIDs = []
  selectedSeatCodes = ""
  $(".seat").on('click', function(event){
    if (this.classList.contains("sold")) {
      return;
    }
    if (this.classList.contains("selected")) {
      this.classList.remove("selected");
      index = selectedSeatIDs.indexOf(this.id);
      selectedSeatIDs.splice(index, 1)
      $("#seatCount")[0].innerText = Number($("#seatCount")[0].innerText) - 1;
      reduceCost(this);
    } else {
      this.classList.add("selected");
      selectedSeatIDs.push(this.id);
      $("#seatCount")[0].innerText = Number($("#seatCount")[0].innerText) + 1;
      addCost(this);
    }
    checkAndActivateConfirmButton();
  });

  $("#confirmButton").on('click', function(event){
    if(selectedSeatIDs.length == 0){
      return
    }
    showID = #{params[:show_id]}
    $.ajax({
      url: "/shows/" + showID + "/bookings",
      type: "POST",
      datatype: "json",
      data: {seat_ids: selectedSeatIDs},
      success:function(data){
        selectedSeatCodes = data.data.seat_codes;
        console.log(selectedSeatCodes)
        totalCost = $("#totalCost")[0].innerText
        $('#totalCost2')[0].innerText = totalCost
        $('#selectedSeatCodes')[0].innerText = selectedSeatCodes
        $('#modal-window').modal('show');
      }
    })
  })

  function addCost(seat) {
    costElement = $("#totalCost")[0]
    classList = seat.classList
    if (classList.contains("silver")){
      costElement.innerText = Number(costElement.innerText) + 150;
    } else if (classList.contains("gold")){
      costElement.innerText = Number(costElement.innerText) + 200;
    } else if (classList.contains("platinum")){
      costElement.innerText = Number(costElement.innerText) + 300;
    }
  }

  function reduceCost(seat) {
    costElement = $("#totalCost")[0]
    classList = seat.classList
    if (classList.contains("silver")){
      costElement.innerText = Number(costElement.innerText) - 150;
    } else if (classList.contains("gold")){
      costElement.innerText = Number(costElement.innerText) - 200;
    } else if (classList.contains("platinum")){
      costElement.innerText = Number(costElement.innerText) - 300;
    }
  }

  function checkAndActivateConfirmButton() {
    confirmButton = $("#confirmButton")[0];
    if($(".selected").length == 0) {
      confirmButton.classList.add("disabled");
    } else {
      confirmButton.classList.remove("disabled");
    }
  }

app/views/dashboard/welcome.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %title BookMyMovie
    %link{:href => "https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i", :rel => "stylesheet"}/
  %body.bg-gradient-primary
    .container
      / Outer Row
      .row.justify-content-center
        .col-xl-10.col-lg-12.col-md-9
          .card.o-hidden.border-0.shadow-lg.my-5
            .card-body.p-0
              / Nested Row within Card Body
              .row
                .col-lg-6.d-none.d-lg-block.bg-login-image
                .col-lg-6
                  .p-5
                    .text-center
                      %h1.h4.text-gray-900.mb-4 Welcome to Book My Movie!
                      .text.font-weight-bold.text-secondary.mb-1 We are an online platform where you can book your favorite movies in a few easy steps.
                      %br
                      %br
                      %br
                      = link_to 'Book My Movie', shows_path(date: Date.today),  {class: 'btn btn-info btn-lg'}
                      %br
                      %br
                      %br
                      %br
                      = link_to 'Are you an Admin? Login here', new_user_session_path,  {class: 'small'}

app/views/shows/_filters.haml
.row.mt-4
  .col-2.text-info.font-weight-bold
    Date
  .col-2.text-info.font-weight-bold
    Movie
  .col-2.text-info.font-weight-bold
    Timing
.row
  .col-2
    = date_field_tag "date", params[:date], class: 'form-control', disabled: false, min: Date.today
  .col-2
    = select_tag "movie_id", options_for_select(Movie.dropdown_list, params[:movie_id]), |
      options = {:class => "form-control", :prompt => 'All'}
  .col-2
    = select_tag "time_slot", options_for_select(Show::TIMINGS.invert.to_a, params[:time_slot]), |
      options = {:class => "form-control", :prompt => 'All'}

app/views/shows/_list.haml
.card.shadow.mb-4.mt-4.border-left-primary.border-bottom-primary
  .card-header
    .row
      .col-lg-10
        %h6.m-0.font-weight-bold.text-info Shows
  .card-body
    .table-responsive
      %table#dataTable.table.table-bordered{:cellspacing => "0", :width => "100%"}
        %thead
          %tr
            %th Movie
            %th Timings
            %th Available Seats
            %th Book
        %tbody
          - @shows.each do |show|
            %tr
              %td= show.movie.name
              %td= Show::TIMINGS.as_json[show.time_slot]
              %td= 100 - show.bookings.count
              %td
                = link_to 'Book My Movie', new_show_booking_path(show.id),  {class: 'btn btn-info btn-sm'}

app/views/users/dashboard.haml
%h BRO